### ISSUE TITLE
Setting synthetic monitoring app as default dashboard in grafana.ini doesn't work

### ISSUE THREAD

**Issue by rbudiharso** [grafana/synthetic-monitoring-app#281]
**What happened**:
When setting synthetic monitoring app as default home dashboard in grafana.ini result in error as in screenshot. The related config is `dashboards.default_home_dashboard_path`.

**What you expected to happen**:
Synthetic monitoring app can be set as default dashboard

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy grafana using helm chart (grafana/grafana)
- set the helm values `grafana.ini` as:
```
grafana.ini:
  dashboards:
    default_home_dashboard_path: /a/grafana-synthetic-monitoring-app/?page=redirect&dashboard=summary
  server:
    domain: grafana.example.com
    root_url: http://grafana.example.com
```

**Anything else we need to know?**:

**Environment**:
- Grafana version (if running on prem): 7.5.7
- SM plugin version: 0.10.2
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Fedora 34, Firefox 88
- Others:

![screenshot-20210604-154457](https://user-images.githubusercontent.com/43447/120773789-dd3e5180-c54b-11eb-9dd2-805d0828fb20.png)
![screenshot-20210604-154404](https://user-images.githubusercontent.com/43447/120773795-de6f7e80-c54b-11eb-9583-00a717013697.png)
