### ISSUE TITLE
Unable to configure Synthetic monitoring on docker installation

### ISSUE THREAD

**Issue by anuj9196** [grafana/synthetic-monitoring-app#311]
**What happened**:
I setup the grafana 8.0.1 with docker-compose.

```
services:
  grafana:
    image: grafana/grafana:8.0.1
    container_name: grafania
    volumes:
    - grafana_storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-synthetic-monitoring-app,grafana-worldmap-panel'
    ports:
    - 80:3000
    restart: always

volumes:
  grafana_storage:
```

While configuring the Synthetic monitoring plugin, it asked for Admin API Key.

1. In the first step I generated an API key in the local installation with Admin rights and used that key to validate synthetic monitoring but it failed with error **Invalid Credentials**
2. I created an account on the grafana cloud and generated an API key there and used that in my local installation and it worked.

But still, the Synthetic monitoring option is not appearing in the sidebar
![Screenshot 2021-06-12 at 8 00 46 AM](https://user-images.githubusercontent.com/6560085/121762652-f9964b80-cb54-11eb-89ed-f8d4f1568887.png)

**What you expected to happen**:
1. If grafana promises to be open source and allows installation on its own server, there should be no requirement of the grafana cloud account.
2. After installation of the Synthetic monitoring plugin, it should appear in the sidebar navigation.

**How to reproduce it (as minimally and precisely as possible)**:
You can use the above docker-compose script to run a copy of grafana with the plugin installed and try setting it up.

**Anything else we need to know?**:

**Environment**:
- Grafana version (if running on prem): 8.0.1
- SM plugin version: 1.0.9
- OS Grafana is installed on: Ubuntu (docker)
- User OS & Browser: MacOS (Chrome)
- Others:
