### ISSUE TITLE
Adhoc tests utilize the wrong Loki datasource when looking for a response and timeout

### ISSUE THREAD

**Issue by ckbedwell** [grafana/synthetic-monitoring-app#844]
**What happened**:
In certain situations when you have multiple Loki datasources set-up in your instance, when utilizing the test button on the check form the UI says 'timed out waiting for a response'. This can be seen in [Grafana Ops](https://ops.grafana-ops.net/a/grafana-synthetic-monitoring-app/checks/edit/http/223) currently when utilizing the test button for **any** check.

![A screenshot of the Synthetic Monitoring plugin with the test results modal open. It shows that the test has timed out whilst waiting for a response.](https://github.com/grafana/synthetic-monitoring-app/assets/6906380/3d8c06ff-391b-4cb7-8210-de369dd2688f)

**What you expected to happen**:
That the correct Loki datasource is queried and we get the right logs instead of a false timeout.

**How to reproduce it (as minimally and precisely as possible)**:
In my local set-up I can repro this by provisioning an extra Loki instance and adding it to my datasource provisioning set-up:

```
- name: grafanacloud-ckbedwellksix-logs
    type: loki
    access: proxy
    url: https://logs-dev-005.grafana-dev.net
    basicAuth: true
    basicAuthUser:<user>
    secureJsonData:
      basicAuthPassword: <password>
    jsonData:
      maxLines: 1000
  - name: Loki
    uid: grafanacloud-logs
    type: loki
    url: https://logs-dev-005.grafana-dev.net
    basicAuth: true
    basicAuthUser:<user>
    isDefault: false
    secureJsonData:
      basicAuthPassword: <password>
    jsonData:
      derivedFields:
        - datasourceUid: grafanacloud-traces
          matcherRegex: '[tT]race_?[iI][dD]\"?[:=]\"?(\\w+)'
          name: traceID
          url: ${__value.raw}
      timeout: 300
```
